#!/usr/bin/env perl
# generated by AI
use strict;
use warnings;

my $indent = 0;
my $INDENT_STR = "  ";

while (<STDIN>) {
    chomp;
    my @chars = split //;
    for my $c (@chars) {
        if ($c eq '(') {
            print "(\n";
            $indent++;
            print $INDENT_STR x $indent;
        } elsif ($c eq ')') {
            print "\n";
            $indent-- if $indent > 0;
            print $INDENT_STR x $indent;
            print ")";
        } elsif ($c eq ',') {
            print ",\n";
            print $INDENT_STR x $indent;
        } else {
            print $c;
        }
    }
}
print "\n";
